import { Inter } from "next/font/google";
import "./globals.css";
import Loading from "./loading";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tuhoyee Family Tree",
  description: "Generated by Tuhoyee Family Tree",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
      </head>
      <body className={inter.className}>
        <div className="pt-[76px]">
          <main className="container mx-auto px-4 mt-1">
            <Suspense fallback={<Loading />}>
              {children}
            </Suspense>
          </main>
        </div>
      </body>
    </html>
  );
}
